<a href="https://colab.research.google.com/github/kiruba-285/ML-Predictions---Google-Colab/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to a pandas DataFrame
credit_card_data = pd.read_csv("/content/creditcard.csv")

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
19893,30631,-0.377215,0.973528,1.647077,0.732439,0.024728,-0.541379,0.828488,-0.060740,-0.725148,...,0.228443,0.685913,-0.107687,0.631740,0.126366,-0.327633,0.056522,0.033139,29.90,0.0
19894,30631,1.209281,0.078793,0.061820,0.593730,-0.235772,-0.448524,-0.141196,0.089236,0.411825,...,-0.302369,-0.984051,0.130401,-0.390756,0.105615,0.152881,-0.025292,0.021130,16.00,0.0
19895,30632,1.286596,-1.450336,0.814530,-1.308949,-2.055209,-0.592064,-1.317286,0.032386,-1.720017,...,0.040743,0.262534,-0.045112,0.515660,0.218606,-0.138794,0.026395,0.030885,92.00,0.0
19896,30633,-0.488090,1.018448,0.670593,-0.245462,0.828347,-0.233102,0.662586,-0.040028,-0.279439,...,-0.344859,-0.902035,-0.050171,-1.060827,0.062221,0.150428,0.130266,0.067290,1.99,0.0
19897,30633,-2.609841,2.479357,0.763844,0.044509,-0.645716,0.762867,-1.626415,-7.617854,1.399746,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#data set information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19898 entries, 0 to 19897
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    19898 non-null  int64
 1   V1      19898 non-null  float64
 2   V2      19898 non-null  float64
 3   V3      19898 non-null  float64
 4   V4      19898 non-null  float64
 5   V5      19898 non-null  float64
 6   V6      19898 non-null  float64
 7   V7      19898 non-null  float64
 8   V8      19898 non-null  float64
 9   V9      19898 non-null  float64
 10  V10     19898 non-null  float64
 11  V11     19897 non-null  float64
 12  V12     19897 non-null  float64
 13  V13     19897 non-null  float64
 14  V14     19897 non-null  float64
 15  V15     19897 non-null  float64
 16  V16     19897 non-null  float64
 17  V17     19897 non-null  float64
 18  V18     19897 non-null  float64
 19  V19     19897 non-null  float64
 20  V20     19897 non-null  float64
 21  V21     19897 non-null  float64
 22  V22     19897 non-null  float64
 23  V23     19897 non-null  float64
 24  V24     19897 non-null  float64
 25  V25     19897 non-null  float64
 26  V26     19897 non-null  float64
 27  V27     19897 non-null  float64
 28  V28     19897 non-null  float64
 29  Amount  19897 non-null  float64
 30  Class   19897 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 4.7 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    19812
1.0       85
Name: count, dtype: int64

This dataset is highly unbalanced

0 --> Normal Transaction
1 --> Fraudulent Transaction

In [ ]:
#seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(19812, 31)
(85, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    19812.000000
mean        70.169855
std        205.091118
min          0.000000
25%          5.900000
50%         16.070000
75%         59.950000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      85.000000
mean       93.869647
std       261.736641
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#comapare the values of both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,15483.312841,-0.207233,0.215159,0.803126,0.250998,-0.137392,0.104262,-0.108931,0.003328,0.652123,...,0.036041,-0.050458,-0.145393,-0.036602,0.011905,0.121909,0.032495,0.010624,0.006940,70.169855
1.0,17436.164706,-8.862174,6.570214,-12.622087,6.343007,-6.187820,-2.567646,-8.600077,4.519437,-3.041592,...,0.725080,0.536833,-0.395312,-0.385599,-0.275306,0.359543,0.180456,0.907255,0.093985,93.869647

Under-sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions.

Number of fraudulent transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two data frames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
15114,26466,1.188603,0.135141,0.597976,0.565232,-0.587187,-0.797991,-0.071105,-0.036635,-0.131316,...,-0.195399,-0.651219,0.150735,0.512968,0.135490,0.065871,-0.038206,0.010774,8.99,0.0
17606,28823,1.416542,-1.066765,0.610046,-1.231528,-1.694514,-0.870885,-1.008321,-0.108759,-1.782280,...,-0.152924,-0.074196,0.128729,0.577654,0.216191,-0.208937,0.040411,0.023560,25.00,0.0
12033,20829,1.284475,-0.528597,-0.551952,-1.692217,1.390419,3.487251,-1.223489,0.875786,2.954982,...,-0.208136,-0.272552,-0.070785,0.957666,0.636471,-0.711079,0.068018,0.024173,11.85,0.0
19518,30346,1.388250,-0.448276,-0.014747,-0.717510,-0.547213,-0.556434,-0.302841,-0.186374,-1.146845,...,0.197548,0.618484,-0.237182,0.095506,0.832889,-0.066941,-0.008824,-0.005754,20.00,0.0
18807,29784,-1.189160,-0.912282,-0.020780,-1.583873,-0.503118,-0.010237,2.305826,-0.554677,0.224097,...,-0.181976,-0.387607,0.408190,-0.281213,-0.454323,-0.297243,-0.055896,-0.023755,445.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
17480,28755,-30.552380,16.713389,-31.103685,6.534984,-22.105532,-4.977692,-20.371514,20.007208,-3.565738,...,1.816520,-2.288686,-1.460544,0.183179,2.208209,-0.208824,1.232636,0.356660,99.99,1.0
18466,29526,1.102804,2.829168,-3.932870,4.707691,2.937967,-1.800904,1.672734,-0.300240,-2.783011,...,-0.106994,-0.250050,-0.521627,-0.448950,1.291646,0.516327,0.009146,0.153318,0.68,1.0
18472,29531,-1.060676,2.608579,-2.971679,4.360089,3.738853,-2.728395,1.987616,-0.357345,-2.757535,...,-0.063168,-0.207385,-0.183261,-0.103679,0.896178,0.407387,-0.130918,0.192177,0.68,1.0
18773,29753,0.269614,3.549755,-5.810353,5.809370,1.538808,-2.269219,-0.824203,0.351070,-3.759059,...,0.371121,-0.322290,-0.549856,-0.520629,1.378210,0.564714,0.553255,0.402400,0.68,1.0
18809,29785,0.923764,0.344048,-2.880004,1.721680,-3.019565,-0.639736,-3.801325,1.299096,0.864065,...,0.899931,1.481271,0.725266,0.176960,-1.815638,-0.536517,0.489035,-0.049729,30.30,1.0

In [ ]:
#checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     85
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,15706.272358,-0.331592,0.243727,0.780526,0.222259,-0.154441,0.033582,-0.138119,-0.072634,0.587821,...,0.071484,-0.105067,-0.127481,-0.035650,0.046158,0.116552,0.030083,0.029923,0.028553,75.510996
1.0,17436.164706,-8.862174,6.570214,-12.622087,6.343007,-6.187820,-2.567646,-8.600077,4.519437,-3.041592,...,0.725080,0.536833,-0.395312,-0.385599,-0.275306,0.359543,0.180456,0.907255,0.093985,93.869647

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time         V1         V2         V3        V4         V5        V6  \
15114  26466   1.188603   0.135141   0.597976  0.565232  -0.587187 -0.797991
17606  28823   1.416542  -1.066765   0.610046 -1.231528  -1.694514 -0.870885
12033  20829   1.284475  -0.528597  -0.551952 -1.692217   1.390419  3.487251
19518  30346   1.388250  -0.448276  -0.014747 -0.717510  -0.547213 -0.556434
18807  29784  -1.189160  -0.912282  -0.020780 -1.583873  -0.503118 -0.010237
...      ...        ...        ...        ...       ...        ...       ...
17480  28755 -30.552380  16.713389 -31.103685  6.534984 -22.105532 -4.977692
18466  29526   1.102804   2.829168  -3.932870  4.707691   2.937967 -1.800904
18472  29531  -1.060676   2.608579  -2.971679  4.360089   3.738853 -2.728395
18773  29753   0.269614   3.549755  -5.810353  5.809370   1.538808 -2.269219
18809  29785   0.923764   0.344048  -2.880004  1.721680  -3.019565 -0.639736

              V7         V8        V9  ...       V20       V21       V22  \
15114  -0.071105  -0.036635 -0.131316  ... -0.115698 -0.195399 -0.651219
17606  -1.008321  -0.108759 -1.782280  ... -0.398608 -0.152924 -0.074196
12033  -1.223489   0.875786  2.954982  ... -0.015415 -0.208136 -0.272552
19518  -0.302841  -0.186374 -1.146845  ...  0.150228  0.197548  0.618484
18807   2.305826  -0.554677  0.224097  ...  0.285120 -0.181976 -0.387607
...          ...        ...       ...  ...       ...       ...       ...
17480 -20.371514  20.007208 -3.565738  ...  1.733644  1.816520 -2.288686
18466   1.672734  -0.300240 -2.783011  ... -0.030880 -0.106994 -0.250050
18472   1.987616  -0.357345 -2.757535  ... -0.089062 -0.063168 -0.207385
18773  -0.824203   0.351070 -3.759059  ...  0.310525  0.371121 -0.322290
18809  -3.801325   1.299096  0.864065  ...  0.170872  0.899931  1.481271

            V23       V24       V25       V26       V27       V28  Amount
15114  0.150735  0.512968  0.135490  0.065871 -0.038206  0.010774    8.99
17606  0.128729  0.577654  0.216191 -0.208937  0.040411  0.023560   25.00
12033 -0.070785  0.957666  0.636471 -0.711079  0.068018  0.024173   11.85
19518 -0.237182  0.095506  0.832889 -0.066941 -0.008824 -0.005754   20.00
18807  0.408190 -0.281213 -0.454323 -0.297243 -0.055896 -0.023755  445.00
...         ...       ...       ...       ...       ...       ...     ...
17480 -1.460544  0.183179  2.208209 -0.208824  1.232636  0.356660   99.99
18466 -0.521627 -0.448950  1.291646  0.516327  0.009146  0.153318    0.68
18472 -0.183261 -0.103679  0.896178  0.407387 -0.130918  0.192177    0.68
18773 -0.549856 -0.520629  1.378210  0.564714  0.553255  0.402400    0.68
18809  0.725266  0.176960 -1.815638 -0.536517  0.489035 -0.049729   30.30

[577 rows x 30 columns]

In [ ]:
print(Y)

15114    0.0
17606    0.0
12033    0.0
19518    0.0
18807    0.0
        ...
17480    1.0
18466    1.0
18472    1.0
18773    1.0
18809    1.0
Name: Class, Length: 577, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(577, 30) (461, 30) (116, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
#training the Logistic  Regerssion Model with Training Data
model.fit(X_train,Y_train)

NameError: name 'model' is not defined

Model Evaluation

Accuracy Score

In [ ]:
#accuracy on training Data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
print("Accuracy on Training data : ", training_data_accuracy) # corrected the variable name from training_data_acccuracy to training_data_accuracy

Accuracy on Training data :  0.9566160520607375

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [ ]:
print("Accuracy Score on Test Data:", test_data_accuracy)

Accuracy Score on Test Data: 0.9310344827586207